/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "solana-blockmeter-api": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "solana-blockmeter-postgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "solana-blockmeter-redis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "solana-blockmeter-vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "solana-blockmeter-web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}